trigger:
- main

pool:
  name: Default

steps:
- task: Docker@2
  displayName: 'Docker 이미지 빌드'
  inputs:
    command: build
    repository: atobgd
    Dockerfile: Dockerfile
    tags: $(Build.BuildId)
